RaterML/urls.py
from django.contrib import admin
from django.urls import path
from main_app import views
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('main_app/',include('main_app.urls')),
    path('health_manager/',include('health_manager.urls'))
]

app/urls.py
from django.urls import path
from app import views

urlpatterns = [
    path(r'',views.index,name='index'),
]

health_manager/urls.py
from django.urls import path
from health_manager import views

app_name = 'health_manager'

urlpatterns = [
    path(r'health/',views.health,name='health'),
]

main_app/urls.py
from django.urls import path
from main_app import views

app_name='main_app'
urlpatterns = [

]

health_manager/models.py
from django.db import models
import datetime
# Create your models here.
class Weight(models.Model):
    lb= models.DecimalField(max_digits=5,decimal_places=2)
    datetime = models.DateTimeField()
    def __str__(self):
        return self.datetime.strftime("%Y-%m-%d")+'\tweight:'+str(self.lb)

main_app/models.py
from django.db import models

# Create your models here.


class Topic(models.Model):
    top_name = models.CharField(max_length=264,unique=True)

    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    name = models.CharField(max_length=264,unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage,on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

health_manager/forms.py
from django import forms
from health_manager.models import Weight

class NewWeightForm(forms.ModelForm):
    class Meta():
        model = Weight
        fields = '__all__'

app/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return HttpResponse("Hello World")

health_manager/views.py
from django.shortcuts import render
from django.http import HttpRequest
from health_manager.models import Weight
from health_manager.forms import NewWeightForm

# Create your views here.
def health(request):
    form = NewWeightForm()
    if request.method=="POST":
        form = NewWeightForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
        else:
            print("INVALID FORM")
    weights = Weight.objects.order_by('datetime')
    context = {'weights':weights,
               'form':form}
    return render(request,'health_manager/health.html',context)

main_app/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request,'main_app/index.html')

templates/health_manager/health.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Health Manager</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
  <body>
    <nav class="navbar navbar-inverse" data-spy="affix" data-offset-top="197">
  <ul class="nav navbar-nav">
    <li class="active"><a href="{%url 'index'%}">Home</a></li>
    <li><a href="{%url 'health_manager:health'%}">Health</a></li>
    <li><a href="{%url 'index'%}">Back Home</a></li>
    <li><a href="{%url 'admin:index'%}">Admin</a></li>
  </ul>
</nav>

<!-- -->
    <div class="container">
      <div class="jumbotron">
        <h1>Health Manager</h1>
      </div>
    </div>

    <div class="container">
      <form method="POST">
        {{form.as_p}}
        {%csrf_token%}
        <input type="submit" class='btn btn-primary' value="Submit">
      </form>

    </div>



    <div class="container">
      <h2>Weight Records</h2>
      <input class="form-control" id="myInput" type="text" placeholder="Search..">
      <br>
        <table class="table table-bordered table-striped">
          <thead>
            <th>Date</th>
            <th>Weight in LB</th>
          </thead>
          <tbody id="weights_table">
            {%for w in weights%}
            <tr>
              <td>{{w.datetime}}</td>
              <td>{{w.lb}}</td>
            </tr>
            {%endfor%}
          </tbody>

        </table>
    </div>


  </body>
</html>

<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#weights_table tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>

templates/main_app/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>HOME</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <h1>RaterML HOME</h1>
    <a href="{%url 'health_manager:health'%}">Health Management</a>
  </body>
</html>